apiVersion: apps/v1
kind: Deployment
metadata:
	name: ngnix-deployment
spec:
	repicas: 2
	selector:
		matchLabels:
			app: ngnix
	template:
		metadata:
			labels:
				app: ngnix
		spec:
			containers:
			- name: ngnix
			  image: ngnix:1.16
			  resources:
			  	limits:
				  memory: "256Mi"
				  cpu: "500m"
			  ports:
			  - containerPort: 8080
