apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
   -  name: flask-app-container
      image: {{ .Values.app.imageName }}/{{ .Values.app.repoName }}:latest
      volumeMounts:
      - name: config-vol
        mountPath: /config
      - name: secret-vol
        mountPath: /config2
        readOnly: true

  volumes:
    - name: config-vol
      configMap:
        name: app-rohit-config
    - name: secret-vol
      secret: 
        secretName: mysecrets
