{{- if .Values.serviceenabled -}}
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: MyApp
  ports:
    {{- toYaml .Values.app.ports | nindent 4 }}
  type: LoadBalancer
{{- end -}}